all:Cuda_9a

Cuda_9a: AuxillaryData.o GetDeviceData.o Backend_Host.o
	nvcc AuxillaryData.o GetDeviceData.o Backend_Host.o

AuxillaryData.o: AuxillaryData.cu
	nvcc -c AuxillaryData.cu

GetDeviceData.o: GetDeviceData.cu
	nvcc -c GetDeviceData.cu

Backend_Host.o: Backend_Host.cu
	nvcc -c Backend_Host.cu

clean:
	rm -rf *.o Cuda_9a
